from news_breakout.config import load_settings

# Minimal config covering every required top-level section, used by tests that only
# care about a handful of optional keys. `news:` and `portal:` are written as
# recognizable substrings so tests can .replace() specific keys in without
# reproducing the whole document.
_MINIMAL_YAML = (
    "watchlist: [ANTM]\n"
    "signals: {donchian_lookback: 20, rvol_threshold: 2.0, rvol_window: 20, "
    "range_lookback: 30, range_max_width_pct: 0.15}\n"
    "data: {history_days: 120, intraday_period_days: 60}\n"
    "runtime: {dry_run: true}\n"
    "schedule: {market_open: \"09:00\", market_close: \"16:00\", scan_interval_minutes: 30, "
    "weekend_scan_day: \"sat\", holidays: []}\n"
    "universe: {candidates: [], min_price: 50, min_daily_value: 1000000000}\n"
    "news: {curated_keywords: [dividen], disclosure_page_size: 50, "
    "news_poll_interval_minutes: 60}\n"
    "portal: {enabled: true}\n"
)


def _load(cfg_path, monkeypatch):
    """Load settings from cfg_path, monkeypatching in the required TELEGRAM_* env vars.

    Points env_path at a file that does not exist so `_load_env_file` no-ops and the
    monkeypatched env vars are what `load_settings` reads.
    """
    monkeypatch.setenv("TELEGRAM_BOT_TOKEN", "a:b")
    monkeypatch.setenv("TELEGRAM_BREAKOUT_CHAT_ID", "-1")
    monkeypatch.setenv("TELEGRAM_NEWS_CHAT_ID", "-2")
    return load_settings(str(cfg_path), env_path=str(cfg_path.parent / "absent.env"))


def test_load_settings_merges_yaml_and_env(tmp_path):
    cfg = tmp_path / "config.yaml"
    cfg.write_text(
        "watchlist: [ANTM, BBRI]\n"
        "signals: {donchian_lookback: 20, rvol_threshold: 2.0, rvol_window: 20, "
        "range_lookback: 30, range_max_width_pct: 0.15}\n"
        "data: {history_days: 120, intraday_period_days: 60}\n"
        "runtime: {dry_run: true}\n"
        "schedule: {market_open: \"09:00\", market_close: \"16:00\", scan_interval_minutes: 30, "
        "weekend_scan_day: \"sat\", holidays: [\"2026-01-01\"]}\n"
        "universe: {candidates: [], min_price: 50, min_daily_value: 1000000000}\n"
        "news: {curated_keywords: [dividen], disclosure_page_size: 50, "
        "news_poll_interval_minutes: 60, booster_window_hours: 72, priority_boost: 4.0}\n"
        # pin name_map_file to an absent path so a real config/name_map.yaml in the
        # repo (generated by scripts/build_name_map.py) can't leak into this test
        f"portal: {{name_map_file: {(tmp_path / 'absent.yaml').as_posix()}}}\n",
        encoding="utf-8",
    )
    env = tmp_path / ".env"
    env.write_text(
        "TELEGRAM_BOT_TOKEN=abc:123\nTELEGRAM_BREAKOUT_CHAT_ID=-100999\n"
        "TELEGRAM_NEWS_CHAT_ID=-200\n",
        encoding="utf-8",
    )

    s = load_settings(str(cfg), str(env))

    assert s.watchlist == ["ANTM", "BBRI"]
    assert s.donchian_lookback == 20
    assert s.rvol_threshold == 2.0
    assert s.rvol_window == 20
    assert s.history_days == 120
    assert s.range_lookback == 30
    assert s.range_max_width_pct == 0.15
    assert s.intraday_period_days == 60
    assert s.dry_run is True
    assert s.telegram_bot_token == "abc:123"
    assert s.telegram_breakout_chat_id == "-100999"
    assert s.market_open == "09:00"
    assert s.scan_interval_minutes == 30
    assert s.weekend_scan_day == "sat"
    assert s.holidays == ["2026-01-01"]
    assert s.universe_candidates == []
    assert s.min_price == 50
    assert s.min_daily_value == 1000000000
    assert s.telegram_news_chat_id == "-200"
    assert s.curated_keywords == ["dividen"]
    assert s.disclosure_page_size == 50
    assert s.news_poll_interval_minutes == 60
    assert s.idx_proxy == ""
    assert s.news_booster_window_hours == 72
    assert s.news_priority_boost == 4.0
    assert s.portal_enabled is False
    assert s.portal_sources == []
    assert s.portal_name_map == {}


def test_load_settings_reads_portal_section(tmp_path):
    cfg = tmp_path / "config.yaml"
    cfg.write_text(
        "watchlist: [ANTM, BBRI]\n"
        "signals: {donchian_lookback: 20, rvol_threshold: 2.0, rvol_window: 20, "
        "range_lookback: 30, range_max_width_pct: 0.15}\n"
        "data: {history_days: 120, intraday_period_days: 60}\n"
        "runtime: {dry_run: true}\n"
        "schedule: {market_open: \"09:00\", market_close: \"16:00\", scan_interval_minutes: 30, "
        "weekend_scan_day: \"sat\", holidays: [\"2026-01-01\"]}\n"
        "universe: {candidates: [], min_price: 50, min_daily_value: 1000000000}\n"
        "news: {curated_keywords: [dividen], disclosure_page_size: 50, "
        "news_poll_interval_minutes: 60}\n"
        "portal: {enabled: true, sources: [\"https://www.kontan.co.id/rss\"], "
        "name_map: {barito pacific: BRPT}, "
        # absent path: keep the repo's generated name_map.yaml out of this test
        f"name_map_file: {(tmp_path / 'absent.yaml').as_posix()}}}\n",
        encoding="utf-8",
    )
    env = tmp_path / ".env"
    env.write_text(
        "TELEGRAM_BOT_TOKEN=abc:123\nTELEGRAM_BREAKOUT_CHAT_ID=-100999\n"
        "TELEGRAM_NEWS_CHAT_ID=-200\n",
        encoding="utf-8",
    )

    s = load_settings(str(cfg), str(env))

    assert s.portal_enabled is True
    assert s.portal_sources == ["https://www.kontan.co.id/rss"]
    assert s.portal_name_map == {"barito pacific": "BRPT"}


def test_load_settings_reads_portal_dict_sources_with_parser(tmp_path):
    cfg = tmp_path / "config.yaml"
    cfg.write_text(
        "watchlist: [ANTM, BBRI]\n"
        "signals: {donchian_lookback: 20, rvol_threshold: 2.0, rvol_window: 20, "
        "range_lookback: 30, range_max_width_pct: 0.15}\n"
        "data: {history_days: 120, intraday_period_days: 60}\n"
        "runtime: {dry_run: true}\n"
        "schedule: {market_open: \"09:00\", market_close: \"16:00\", scan_interval_minutes: 30, "
        "weekend_scan_day: \"sat\", holidays: [\"2026-01-01\"]}\n"
        "universe: {candidates: [], min_price: 50, min_daily_value: 1000000000}\n"
        "news: {curated_keywords: [dividen], disclosure_page_size: 50, "
        "news_poll_interval_minutes: 60}\n"
        "portal: {enabled: true, sources: ["
        "{url: \"https://www.kontan.co.id/rss\", parser: rss}, "
        "{url: \"https://emitennews.com/category/emiten\", parser: emitennews}"
        "], name_map: {barito pacific: BRPT}}\n",
        encoding="utf-8",
    )
    env = tmp_path / ".env"
    env.write_text(
        "TELEGRAM_BOT_TOKEN=abc:123\nTELEGRAM_BREAKOUT_CHAT_ID=-100999\n"
        "TELEGRAM_NEWS_CHAT_ID=-200\n",
        encoding="utf-8",
    )

    s = load_settings(str(cfg), str(env))

    assert s.portal_enabled is True
    assert s.portal_sources == [
        {"url": "https://www.kontan.co.id/rss", "parser": "rss"},
        {"url": "https://emitennews.com/category/emiten", "parser": "emitennews"},
    ]


def test_load_settings_falls_back_to_booster_defaults_when_absent(tmp_path):
    cfg = tmp_path / "config.yaml"
    cfg.write_text(
        "watchlist: [ANTM, BBRI]\n"
        "signals: {donchian_lookback: 20, rvol_threshold: 2.0, rvol_window: 20, "
        "range_lookback: 30, range_max_width_pct: 0.15}\n"
        "data: {history_days: 120, intraday_period_days: 60}\n"
        "runtime: {dry_run: true}\n"
        "schedule: {market_open: \"09:00\", market_close: \"16:00\", scan_interval_minutes: 30, "
        "weekend_scan_day: \"sat\", holidays: [\"2026-01-01\"]}\n"
        "universe: {candidates: [], min_price: 50, min_daily_value: 1000000000}\n"
        "news: {curated_keywords: [dividen], disclosure_page_size: 50, "
        "news_poll_interval_minutes: 60}\n",
        encoding="utf-8",
    )
    env = tmp_path / ".env"
    env.write_text(
        "TELEGRAM_BOT_TOKEN=abc:123\nTELEGRAM_BREAKOUT_CHAT_ID=-100999\n"
        "TELEGRAM_NEWS_CHAT_ID=-200\n",
        encoding="utf-8",
    )

    s = load_settings(str(cfg), str(env))

    assert s.news_booster_window_hours == 48
    assert s.news_priority_boost == 3.0


def test_load_settings_reads_curation_keys(tmp_path):
    cfg = tmp_path / "config.yaml"
    cfg.write_text(
        "watchlist: [ANTM]\n"
        "signals: {donchian_lookback: 20, rvol_threshold: 2.0, rvol_window: 20, "
        "range_lookback: 30, range_max_width_pct: 0.15}\n"
        "data: {history_days: 120, intraday_period_days: 60}\n"
        "runtime: {dry_run: true}\n"
        "schedule: {market_open: \"09:00\", market_close: \"16:00\", scan_interval_minutes: 30, "
        "weekend_scan_day: \"sat\", holidays: []}\n"
        "universe: {candidates: [], min_price: 50, min_daily_value: 1000000000}\n"
        "news: {curated_keywords: [dividen], disclosure_page_size: 50, "
        "news_poll_interval_minutes: 60}\n"
        "portal: {enabled: true, sources: [], summary_sentences: 3, max_per_run: 5}\n"
        "sentiment: {enabled: false, model: acme/x, min_confidence: 0.75}\n",
        encoding="utf-8",
    )
    env = tmp_path / ".env"
    env.write_text("TELEGRAM_BOT_TOKEN=a:b\nTELEGRAM_BREAKOUT_CHAT_ID=-1\nTELEGRAM_NEWS_CHAT_ID=-2\n",
                   encoding="utf-8")
    s = load_settings(str(cfg), str(env))
    assert s.portal_summary_sentences == 3
    assert s.portal_max_per_run == 5
    assert s.sentiment_enabled is False
    assert s.sentiment_model == "acme/x"
    assert s.sentiment_min_confidence == 0.75


def test_load_settings_curation_defaults_when_absent(tmp_path):
    cfg = tmp_path / "config.yaml"
    cfg.write_text(
        "watchlist: [ANTM]\n"
        "signals: {donchian_lookback: 20, rvol_threshold: 2.0, rvol_window: 20, "
        "range_lookback: 30, range_max_width_pct: 0.15}\n"
        "data: {history_days: 120, intraday_period_days: 60}\n"
        "runtime: {dry_run: true}\n"
        "schedule: {market_open: \"09:00\", market_close: \"16:00\", scan_interval_minutes: 30, "
        "weekend_scan_day: \"sat\", holidays: []}\n"
        "universe: {candidates: [], min_price: 50, min_daily_value: 1000000000}\n"
        "news: {curated_keywords: [dividen], disclosure_page_size: 50, "
        "news_poll_interval_minutes: 60}\n",
        encoding="utf-8",
    )
    env = tmp_path / ".env"
    env.write_text("TELEGRAM_BOT_TOKEN=a:b\nTELEGRAM_BREAKOUT_CHAT_ID=-1\nTELEGRAM_NEWS_CHAT_ID=-2\n",
                   encoding="utf-8")
    s = load_settings(str(cfg), str(env))
    assert s.portal_summary_sentences == 2
    assert s.portal_max_per_run == 20
    assert s.sentiment_enabled is True
    assert s.sentiment_model == "w11wo/indonesian-roberta-base-sentiment-classifier"
    assert s.sentiment_min_confidence == 0.6


def test_load_settings_reads_min_quality_score(tmp_path):
    cfg = tmp_path / "config.yaml"
    cfg.write_text(
        "watchlist: [ANTM]\n"
        "signals: {donchian_lookback: 20, rvol_threshold: 2.0, rvol_window: 20, "
        "range_lookback: 30, range_max_width_pct: 0.15, min_quality_score: 5.5}\n"
        "data: {history_days: 120, intraday_period_days: 60}\n"
        "runtime: {dry_run: true}\n"
        "schedule: {market_open: \"09:00\", market_close: \"16:00\", scan_interval_minutes: 30, "
        "weekend_scan_day: \"sat\", holidays: []}\n"
        "universe: {candidates: [], min_price: 50, min_daily_value: 1000000000}\n"
        "news: {curated_keywords: [dividen], disclosure_page_size: 50, "
        "news_poll_interval_minutes: 60}\n",
        encoding="utf-8",
    )
    env = tmp_path / ".env"
    env.write_text("TELEGRAM_BOT_TOKEN=a:b\nTELEGRAM_BREAKOUT_CHAT_ID=-1\nTELEGRAM_NEWS_CHAT_ID=-2\n",
                   encoding="utf-8")
    s = load_settings(str(cfg), str(env))
    assert s.min_quality_score == 5.5


def test_load_settings_min_quality_score_defaults_to_none(tmp_path):
    cfg = tmp_path / "config.yaml"
    cfg.write_text(
        "watchlist: [ANTM]\n"
        "signals: {donchian_lookback: 20, rvol_threshold: 2.0, rvol_window: 20, "
        "range_lookback: 30, range_max_width_pct: 0.15}\n"
        "data: {history_days: 120, intraday_period_days: 60}\n"
        "runtime: {dry_run: true}\n"
        "schedule: {market_open: \"09:00\", market_close: \"16:00\", scan_interval_minutes: 30, "
        "weekend_scan_day: \"sat\", holidays: []}\n"
        "universe: {candidates: [], min_price: 50, min_daily_value: 1000000000}\n"
        "news: {curated_keywords: [dividen], disclosure_page_size: 50, "
        "news_poll_interval_minutes: 60}\n",
        encoding="utf-8",
    )
    env = tmp_path / ".env"
    env.write_text("TELEGRAM_BOT_TOKEN=a:b\nTELEGRAM_BREAKOUT_CHAT_ID=-1\nTELEGRAM_NEWS_CHAT_ID=-2\n",
                   encoding="utf-8")
    s = load_settings(str(cfg), str(env))
    assert s.min_quality_score is None


def test_load_settings_reads_daily_shift(tmp_path):
    cfg = tmp_path / "config.yaml"
    cfg.write_text(
        "watchlist: [ANTM]\n"
        "signals: {donchian_lookback: 20, rvol_threshold: 2.0, rvol_window: 20, "
        "range_lookback: 30, range_max_width_pct: 0.15}\n"
        "data: {history_days: 120, intraday_period_days: 60}\n"
        "runtime: {dry_run: true}\n"
        "schedule: {market_open: \"09:00\", market_close: \"16:00\", scan_interval_minutes: 30, "
        "weekend_scan_day: \"sat\", holidays: []}\n"
        "universe: {candidates: [], min_price: 50, min_daily_value: 1000000000}\n"
        "news: {curated_keywords: [dividen], disclosure_page_size: 50, "
        "news_poll_interval_minutes: 60}\n"
        "daily_shift: {enabled: false, universe_file: config/x.txt, min_daily_value: 3000000000, "
        "min_price: 100, max_alerts: 10, history_days: 60}\n",
        encoding="utf-8",
    )
    env = tmp_path / ".env"
    env.write_text("TELEGRAM_BOT_TOKEN=a:b\nTELEGRAM_BREAKOUT_CHAT_ID=-1\nTELEGRAM_NEWS_CHAT_ID=-2\n",
                   encoding="utf-8")
    s = load_settings(str(cfg), str(env))
    assert s.daily_shift_enabled is False
    assert s.daily_shift_universe_file == "config/x.txt"
    assert s.daily_shift_min_daily_value == 3000000000
    assert s.daily_shift_min_price == 100
    assert s.daily_shift_max_alerts == 10
    assert s.daily_shift_history_days == 60


def test_load_settings_daily_shift_defaults_when_absent(tmp_path):
    cfg = tmp_path / "config.yaml"
    cfg.write_text(
        "watchlist: [ANTM]\n"
        "signals: {donchian_lookback: 20, rvol_threshold: 2.0, rvol_window: 20, "
        "range_lookback: 30, range_max_width_pct: 0.15}\n"
        "data: {history_days: 120, intraday_period_days: 60}\n"
        "runtime: {dry_run: true}\n"
        "schedule: {market_open: \"09:00\", market_close: \"16:00\", scan_interval_minutes: 30, "
        "weekend_scan_day: \"sat\", holidays: []}\n"
        "universe: {candidates: [], min_price: 50, min_daily_value: 1000000000}\n"
        "news: {curated_keywords: [dividen], disclosure_page_size: 50, "
        "news_poll_interval_minutes: 60}\n",
        encoding="utf-8",
    )
    env = tmp_path / ".env"
    env.write_text("TELEGRAM_BOT_TOKEN=a:b\nTELEGRAM_BREAKOUT_CHAT_ID=-1\nTELEGRAM_NEWS_CHAT_ID=-2\n",
                   encoding="utf-8")
    s = load_settings(str(cfg), str(env))
    assert s.daily_shift_enabled is True
    assert s.daily_shift_universe_file == "config/idx_all.txt"
    assert s.daily_shift_min_daily_value == 2_000_000_000
    assert s.daily_shift_min_price == 50
    assert s.daily_shift_max_alerts == 15
    assert s.daily_shift_history_days == 90


def test_new_news_and_portal_keys_load(tmp_path, monkeypatch):
    cfg = tmp_path / "c.yaml"
    cfg.write_text(_MINIMAL_YAML.replace(
        "news_poll_interval_minutes: 60",
        "news_poll_interval_minutes: 60, booster_page_size: 300, "
        "fetch_cache_ttl_minutes: 5, news_outage_max_failures: 2, "
        "poll_interval_market_minutes: 10, poll_interval_offhours_minutes: 45, "
        "watchlist_passthrough: false, dedup_retention_days: 30",
    ), encoding="utf-8")
    s = _load(cfg, monkeypatch)
    assert s.news_booster_page_size == 300
    assert s.news_fetch_cache_ttl_minutes == 5
    assert s.news_outage_max_failures == 2
    assert s.poll_interval_market_minutes == 10
    assert s.poll_interval_offhours_minutes == 45
    assert s.news_watchlist_passthrough is False
    assert s.news_dedup_retention_days == 30


def test_new_keys_default_and_offhours_falls_back_to_legacy_interval(tmp_path, monkeypatch):
    cfg = tmp_path / "c.yaml"
    cfg.write_text(_MINIMAL_YAML, encoding="utf-8")  # legacy config, no new keys
    s = _load(cfg, monkeypatch)
    assert s.news_booster_page_size == 200
    assert s.news_fetch_cache_ttl_minutes == 10
    assert s.news_outage_max_failures == 4
    assert s.poll_interval_market_minutes == 15
    assert s.poll_interval_offhours_minutes == 60   # falls back to news_poll_interval_minutes
    assert s.news_watchlist_passthrough is True
    assert s.news_dedup_retention_days == 90
    assert s.portal_dup_title_threshold == 0.55
    assert s.portal_fetch_workers == 4
    assert s.portal_proxy == ""


def test_name_map_file_merges_under_inline(tmp_path, monkeypatch):
    nm = tmp_path / "name_map.yaml"
    nm.write_text("aneka tambang: XXXX\nbank rakyat: BBRI\n", encoding="utf-8")
    cfg = tmp_path / "c.yaml"
    cfg.write_text(_MINIMAL_YAML.replace(
        "portal: {enabled: true}",
        "portal: {enabled: true, name_map_file: %s, name_map: {aneka tambang: ANTM}}"
        % nm.as_posix(),
    ), encoding="utf-8")
    s = _load(cfg, monkeypatch)
    assert s.portal_name_map["aneka tambang"] == "ANTM"   # inline wins
    assert s.portal_name_map["bank rakyat"] == "BBRI"     # file entry kept


def test_missing_name_map_file_is_fine(tmp_path, monkeypatch):
    cfg = tmp_path / "c.yaml"
    cfg.write_text(_MINIMAL_YAML.replace(
        "portal: {enabled: true}",
        "portal: {enabled: true, name_map_file: %s}" % (tmp_path / "absent.yaml").as_posix(),
    ), encoding="utf-8")
    s = _load(cfg, monkeypatch)
    assert s.portal_name_map == {}


def test_explicit_null_name_map_file_is_fine(tmp_path, monkeypatch):
    cfg = tmp_path / "c.yaml"
    cfg.write_text(_MINIMAL_YAML.replace(
        "portal: {enabled: true}",
        "portal: {enabled: true, name_map_file: null}",
    ), encoding="utf-8")
    s = _load(cfg, monkeypatch)
    assert s.portal_name_map == {}


def test_corp_action_caution_defaults_true_and_reads_false(tmp_path, monkeypatch):
    cfg = tmp_path / "c.yaml"
    cfg.write_text(_MINIMAL_YAML, encoding="utf-8")
    assert _load(cfg, monkeypatch).news_corp_action_caution is True

    cfg2 = tmp_path / "c2.yaml"
    cfg2.write_text(_MINIMAL_YAML.replace(
        "news_poll_interval_minutes: 60",
        "news_poll_interval_minutes: 60, corp_action_caution: false"), encoding="utf-8")
    assert _load(cfg2, monkeypatch).news_corp_action_caution is False
