"""Generate config/name_map.yaml (lowercase company name -> ticker) from IDX profiles.

Run manually on a machine that can reach idx.co.id (or set IDX_PROXY):
    python scripts/build_name_map.py
    python scripts/build_name_map.py --input profiles.json   # offline: pre-downloaded JSON
The endpoint occasionally shifts; --url overrides it without a code change.
Inline `portal.name_map` entries in config.yaml always override this file.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys

_DEFAULT_URL = ("https://www.idx.co.id/primary/ListedCompany/GetCompanyProfiles"
                "?emitenType=s&start=0&length=1000")
_LEGAL_WORDS = {"pt", "tbk", "persero", "tbk.", "(persero)"}
_MIN_NAME_LEN = 4


def normalize_name(raw: str) -> str:
    tokens = re.findall(r"[a-z0-9]+", (raw or "").lower())
    kept = [t for t in tokens if t not in _LEGAL_WORDS]
    return " ".join(kept)


def _first(record: dict, keys: list[str]) -> str:
    for k in keys:
        v = record.get(k)
        if v:
            return str(v).strip()
    return ""


def build_map(records: list[dict]) -> dict[str, str]:
    out: dict[str, str] = {}
    for rec in records:
        if not isinstance(rec, dict):
            continue
        ticker = _first(rec, ["KodeEmiten", "Kode_Emiten", "kodeEmiten", "Kode"]).upper()
        name = normalize_name(_first(rec, ["NamaEmiten", "Nama_Emiten", "NamaPerusahaan", "Nama"]))
        if not ticker or len(name) < _MIN_NAME_LEN:
            continue
        out[name] = ticker
    return out


def _fetch(url: str, proxy: str) -> list[dict]:
    from news_breakout.news.idx_source import _HEADERS, _PAGE
    from curl_cffi import requests as creq

    kwargs = {"impersonate": "chrome120"}
    if proxy:
        kwargs["proxies"] = {"http": proxy, "https": proxy}
    session = creq.Session(**kwargs)
    try:
        session.get(_PAGE, headers=_HEADERS, timeout=30)  # warm up Cloudflare cookies
    except Exception:  # noqa: BLE001
        pass
    data = json.loads(session.get(url, headers=_HEADERS, timeout=30).text)
    for key in ("data", "Data", "Results", "Replies"):
        if isinstance(data, dict) and isinstance(data.get(key), list):
            return data[key]
    return data if isinstance(data, list) else []


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", help="local JSON file instead of hitting the IDX API")
    ap.add_argument("--out", default="config/name_map.yaml")
    ap.add_argument("--url", default=_DEFAULT_URL)
    args = ap.parse_args()

    if args.input:
        raw = json.loads(open(args.input, encoding="utf-8").read())
        records = raw if isinstance(raw, list) else next(
            (v for v in raw.values() if isinstance(v, list)), [])
    else:
        records = _fetch(args.url, os.environ.get("IDX_PROXY", ""))
    mapping = build_map(records)
    if not mapping:
        print("No records parsed — check --url/--input (endpoint may have shifted).")
        return 1
    lines = [f"{name}: {tk}" for name, tk in sorted(mapping.items())]
    with open(args.out, "w", encoding="utf-8") as f:
        f.write("# generated by scripts/build_name_map.py — inline name_map overrides this\n")
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {len(mapping)} names -> {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
